services:
    redis:
        image: redis:7.4.2-alpine
        container_name: redis
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_USER=${REDIS_USER}
            - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
        ports:
            - "6380:6379"
        volumes:
            - ./redis_data:/data