services:
    web:
        build: .
        container_name: web-app
        volumes:
            - ./src:/app/src
        ports:
            - 8000:8000
        env_file:
            - src/.env
        depends_on:
            - redis
            - prometheus
    redis:
        image: redis:7.4.2-alpine
        container_name: redis
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
            - 6380:6379
        volumes:
            - ./redis_data:/data
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090