services:
    redis:
        image: redis:7.4.2-alpine
        container_name: redis
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
            - "6380:6379"
        volumes:
            - ./redis_data:/data
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - "./prometheus.yml:/etc/prometheus/prometheus.yml"
        ports:
            - 9090:9090